export enum Role {
    'AST.VENDORS' = 'AST.VENDORS',
    'AST.TOP-OFFICIAL' = 'AST.TOP-OFFICIAL',
    'AST.EMPLOYEE' = 'AST.EMPLOYEE',
    'AST.PROCUREMENT' = 'AST.PROCUREMENT',
    'AST.ACCOUNTS' = 'AST.ACCOUNTS',
    'PRC.PE' = 'PRC.PE',
    'AST.DATA-ENTRY-OPERATOR' = 'AST.DATA-ENTRY-OPERATOR',
    'AST.QC-COMMITTEE' = 'AST.QC-COMMITTEE',
    'AST.ASSET-IN-CHARGE' = 'AST.ASSET-IN-CHARGE',
    'PRC.HOPE' = 'PRC.HOPE',
    'PRC.Officer' = 'PRC.Officer',
    'AST.ASSET-MANAGER' = 'AST.ASSET-MANAGER',
    'AST.TAGGING-ENTITY' = 'AST.TAGGING-ENTITY'
}
